/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// ebbinghaus-vocabulary/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => EbbinghausVocabPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// ebbinghaus-vocabulary/src/constants.ts
var DEFAULT_SETTINGS = {
  canvasPaths: [],
  enableTwentyMin: true,
  enableOneHour: true,
  stageIntervals: ["20m", "1h", "1d", "2d", "4d", "7d", "15d", "30d"],
  dailyNewWordLimit: 20,
  heatmapColors: [
    "#ebedf0",
    // Level 0 — empty
    "#9be9a8",
    // Level 1 — low
    "#40c463",
    // Level 2 — medium
    "#30a14e",
    // Level 3 — high
    "#216e39"
    // Level 4 — intense
  ],
  autoIncludeNewWords: true
};
var VIEW_TYPE_REVIEW = "ebbinghaus-review-panel";
var MINUTE_MS = 6e4;
var HOUR_MS = 60 * MINUTE_MS;
var DAY_MS = 24 * HOUR_MS;
function parseInterval(raw) {
  const trimmed = raw.trim();
  const match = trimmed.match(/^(\d+(?:\.\d+)?)\s*(m|h|d)$/i);
  if (!match)
    return null;
  const value = parseFloat(match[1]);
  const unit = match[2].toLowerCase();
  switch (unit) {
    case "m":
      return Math.round(value * MINUTE_MS);
    case "h":
      return Math.round(value * HOUR_MS);
    case "d":
      return Math.round(value * DAY_MS);
    default:
      return null;
  }
}
function buildActiveIntervals(settings) {
  const raw = settings.stageIntervals.map((s) => parseInterval(s));
  if (raw.some((v) => v === null)) {
    return DEFAULT_SETTINGS.stageIntervals.map(
      (s) => parseInterval(s)
    );
  }
  const intervals = raw;
  const result = [];
  for (let i = 0; i < intervals.length; i++) {
    if (i === 0 && !settings.enableTwentyMin)
      continue;
    if (i === 1 && !settings.enableOneHour)
      continue;
    result.push(intervals[i]);
  }
  if (result.length === 0) {
    result.push(DAY_MS);
  }
  return result;
}
function totalStages(intervals) {
  return intervals.length + 1;
}
function dateKey(date) {
  const d = date ?? /* @__PURE__ */ new Date();
  return d.toISOString().slice(0, 10);
}
function heatmapLevel(count) {
  if (count === 0)
    return 0;
  if (count <= 5)
    return 1;
  if (count <= 10)
    return 2;
  if (count <= 20)
    return 3;
  return 4;
}

// ebbinghaus-vocabulary/src/settings.ts
var import_obsidian = require("obsidian");
var EbbinghausSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u{1F4C1} Canvas Files" });
    new import_obsidian.Setting(containerEl).setName("Canvas file paths").setDesc(
      "Relative paths to Canvas files in your vault, one per line. Example: \u8003\u7814\u5355\u8BCD\u672C.canvas"
    ).addTextArea((textarea) => {
      textarea.setPlaceholder("\u8003\u7814\u5355\u8BCD\u672C.canvas\nGRE\u8BCD\u6C47.canvas").setValue(this.plugin.settings.canvasPaths.join("\n")).onChange(async (value) => {
        this.plugin.settings.canvasPaths = value.split("\n").map((p) => p.trim()).filter((p) => p.length > 0);
        await this.plugin.saveSettings();
      });
      textarea.inputEl.rows = 3;
      textarea.inputEl.style.width = "100%";
    });
    containerEl.createEl("h2", { text: "\u23F1 Review Intervals" });
    new import_obsidian.Setting(containerEl).setName("Enable 20-minute interval").setDesc(
      "When enabled, the first review happens 20 minutes after learning. Turn off if you prefer longer intervals."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableTwentyMin).onChange(async (value) => {
        this.plugin.settings.enableTwentyMin = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Enable 1-hour interval").setDesc(
      "When enabled, the second review happens 1 hour after the first. Turn off to go straight to daily reviews."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableOneHour).onChange(async (value) => {
        this.plugin.settings.enableOneHour = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Stage intervals (advanced)").setDesc(
      'Custom review intervals. Use "m" for minutes, "h" for hours, "d" for days. One per line. These define the gap between stages 1 through N. Stage "mastered" is always the last stage.'
    ).addTextArea((textarea) => {
      textarea.setPlaceholder("20m\n1h\n1d\n2d\n4d\n7d\n15d\n30d").setValue(this.plugin.settings.stageIntervals.join("\n")).onChange(async (value) => {
        this.plugin.settings.stageIntervals = value.split("\n").map((p) => p.trim()).filter((p) => p.length > 0);
        await this.plugin.saveSettings();
      });
      textarea.inputEl.rows = 8;
      textarea.inputEl.style.width = "100%";
    });
    containerEl.createEl("h2", { text: "\u{1F4CA} Daily Limits" });
    new import_obsidian.Setting(containerEl).setName("Daily new word limit").setDesc(
      "Maximum number of new words to introduce per day. Set to 0 for unlimited."
    ).addText(
      (text) => text.setPlaceholder("20").setValue(String(this.plugin.settings.dailyNewWordLimit)).onChange(async (value) => {
        const num = parseInt(value, 10);
        this.plugin.settings.dailyNewWordLimit = isNaN(num) ? 0 : Math.max(0, num);
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h2", { text: "\u{1F504} Review Behaviour" });
    new import_obsidian.Setting(containerEl).setName("Auto-include new words").setDesc(
      "When all due words are reviewed, automatically include new words in the session."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoIncludeNewWords).onChange(async (value) => {
        this.plugin.settings.autoIncludeNewWords = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h2", { text: "\u{1F3A8} Heatmap Appearance" });
    const colorLabels = [
      "Empty (0 reviews)",
      "Low (1\u20135)",
      "Medium (6\u201310)",
      "High (11\u201320)",
      "Intense (>20)"
    ];
    for (let i = 0; i < 5; i++) {
      new import_obsidian.Setting(containerEl).setName(colorLabels[i]).addText(
        (text) => text.setPlaceholder("#000000").setValue(this.plugin.settings.heatmapColors[i]).onChange(async (value) => {
          this.plugin.settings.heatmapColors[i] = value.trim() || "#ebedf0";
          await this.plugin.saveSettings();
        })
      );
    }
  }
};

// ebbinghaus-vocabulary/src/word-parser.ts
var _WordParser = class _WordParser {
  /**
   * Parse a single Canvas node into a ParsedWord.
   *
   * @param node   The raw CanvasNode from the JSON
   * @param path   The source Canvas file path (for bookkeeping)
   * @returns      ParsedWord, or `null` if the node text is empty
   */
  parse(node, path) {
    const rawText = node.text?.trim();
    if (!rawText)
      return null;
    const lines = rawText.split("\n").filter((l) => l.trim().length > 0);
    const word = this.stripFormatting(lines[0]).trim();
    if (!word)
      return null;
    let dateOffset = 0;
    let embeddedDate = null;
    if (lines.length > 1 && _WordParser.DATE_RE.test(lines[1].trim())) {
      embeddedDate = lines[1].trim();
      dateOffset = 1;
    }
    const bodyLines = lines.slice(1 + dateOffset);
    const bodyText = bodyLines.join("\n");
    const construction = this.extractSection(bodyText, [
      "\u5355\u8BCD\u6784\u6210",
      "\u5355\u8BCD\u7ED3\u6784",
      "\u6784\u6210"
    ]);
    const definition = this.extractSection(bodyText, [
      "\u5E38\u7528\u4E2D\u6587\u91CA\u4E49",
      "\u4E2D\u6587\u91CA\u4E49",
      "\u91CA\u4E49",
      "\u4E2D\u6587"
    ]);
    const example = this.extractSection(bodyText, ["\u4F8B\u53E5"]);
    const exampleTranslation = this.extractSection(bodyText, ["\u4F8B\u53E5\u7FFB\u8BD1"]);
    const dateStr = embeddedDate || node.ebbingCreatedAt || node.createdAt || null;
    const createdAt = dateStr ? this.parseDate(dateStr) : null;
    const reviewStage = typeof node.ebbingReviewStage === "number" ? node.ebbingReviewStage : 0;
    const nextReview = node.ebbingNextReview ? this.parseDate(node.ebbingNextReview) : null;
    const lastReview = node.ebbingLastReview ? this.parseDate(node.ebbingLastReview) : null;
    const reviewHistory = Array.isArray(node.ebbingReviewHistory) ? node.ebbingReviewHistory : [];
    return {
      nodeId: node.id,
      canvasPath: path,
      word,
      construction,
      definition,
      example,
      exampleTranslation,
      reviewStage,
      nextReview,
      lastReview,
      createdAt,
      reviewHistory,
      rawNode: node
    };
  }
  // ═══════════════════════════════════════════
  // Private helpers
  // ═══════════════════════════════════════════
  /**
   * Strip Markdown bold and HTML tags to get clean plain text.
   * This is non-destructive — we only strip for display, not storage.
   *
   * Handles:
   *   **bold** / __bold__
   *   <span style="color:red;">text</span>
   *   <font color="red">text</font>
   *   <br> → space
   */
  stripFormatting(text) {
    return text.replace(/<[^>]*>/g, "").replace(/\*{1,3}([^*]+)\*{1,3}/g, "$1").replace(/_{1,3}([^_]+)_{1,3}/g, "$1").trim();
  }
  /**
   * Extract the content after a known section label.
   * Supports formats like:
   *   "1) **单词构成**：..."   (label in bold after a number)
   *   "1. **单词构成**：..."   (label in bold after a number)
   *   "1) 单词构成：..."       (label without bold)
   *   "1、单词构成：..."       (Chinese-style numbering)
   *   "**单词构成**：..."      (bold label without number prefix)
   *   "单词构成：..."          (plain label)
   *
   * @param bodyText  The full body text (everything after the word line)
   * @param labels    Possible label strings to match (e.g. ["单词构成", "构成"])
   * @returns         The text after the label, or null if not found
   */
  extractSection(bodyText, labels) {
    for (const label of labels) {
      const escaped = label.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
      const pattern = new RegExp(
        // Optional number prefix: "1)", "1.", "1、", "1）", "1) ", etc.
        // Followed by optional bold markers
        // Followed by the label
        // Followed by optional bold markers
        // Followed by a colon (fullwidth or halfwidth)
        `(?:\\d+[)\\.\u3001\uFF09]\\s*)?\\*{0,2}${escaped}\\*{0,2}\\s*[\uFF1A:]\\s*`,
        "i"
      );
      const match = bodyText.match(pattern);
      if (match) {
        const startIdx = match.index + match[0].length;
        let endIdx = bodyText.indexOf("\n", startIdx);
        const nextSection = bodyText.slice(startIdx).search(/\n\s*\d+[)\\.、）]/);
        if (nextSection !== -1) {
          endIdx = startIdx + nextSection;
        } else if (endIdx === -1) {
          endIdx = bodyText.length;
        }
        let extracted = bodyText.slice(startIdx, endIdx).trim();
        if (nextSection === -1) {
          extracted = bodyText.slice(startIdx).trim();
        }
        extracted = this.stripFormatting(extracted);
        if (extracted.length > 0)
          return extracted;
      }
    }
    if (labels.includes("\u4E2D\u6587\u91CA\u4E49") || labels.includes("\u91CA\u4E49") || labels.includes("\u4E2D\u6587")) {
      const fallback = this.tryFallbackDefinition(bodyText);
      if (fallback)
        return fallback;
    }
    return null;
  }
  /**
   * Fallback for nodes without structured sections.
   * E.g. "extreme\n\na.极端的"
   */
  tryFallbackDefinition(bodyText) {
    const lines = bodyText.split("\n").filter((l) => l.trim().length > 0);
    if (lines.length === 0)
      return null;
    const first = lines[0].trim();
    if (!/^\d+[)\\.、）]/.test(first) && first.length < 100) {
      return this.stripFormatting(first);
    }
    return null;
  }
  /**
   * Parse a date string in various common formats to a Date object.
   * Supported formats:
   *   "2026-06-06 14:13"     (from embedded text)
   *   "2026-06-06T14:13:00Z" (ISO-8601)
   *   "2026-06-06"           (date only)
   */
  parseDate(raw) {
    const normalized = raw.trim().replace(" ", "T");
    const date = new Date(normalized);
    return isNaN(date.getTime()) ? /* @__PURE__ */ new Date() : date;
  }
};
/** Regex to match date-like patterns: "2026-06-06 14:13" or "2026-06-06" */
_WordParser.DATE_RE = /^\d{4}-\d{2}-\d{2}(\s+\d{2}:\d{2})?/;
var WordParser = _WordParser;

// ebbinghaus-vocabulary/src/data-manager.ts
var _DataManager = class _DataManager {
  constructor(vault, settings) {
    /** In-memory cache of resolved canvas TFile references, keyed by path */
    this.fileCache = /* @__PURE__ */ new Map();
    /** Pending write debounce timers, keyed by canvas path */
    this.writeTimers = /* @__PURE__ */ new Map();
    /** Plugin statistics, loaded from data.json */
    this.stats = { dailyStats: {} };
    this.vault = vault;
    this.settings = settings;
    this.wordParser = new WordParser();
  }
  // ═══════════════════════════════════════════
  // Public API
  // ═══════════════════════════════════════════
  /**
   * Load all word nodes from all configured Canvas files.
   * Only returns nodes that have a date marker (ebbingCreatedAt or createdAt in text).
   *
   * @returns ParsedWord array, sorted by nextReview (ascending, nulls last)
   */
  async loadAllWords() {
    const paths = this.settings.canvasPaths;
    const allWords = [];
    for (const path of paths) {
      const file = await this.resolveFile(path);
      if (!file)
        continue;
      const nodes = await this.readTextNodes(file);
      for (const node of nodes) {
        const parsed = this.wordParser.parse(node, path);
        if (parsed && parsed.createdAt !== null) {
          allWords.push(parsed);
        }
      }
    }
    allWords.sort((a, b) => {
      if (a.nextReview === null && b.nextReview === null)
        return 0;
      if (a.nextReview === null)
        return 1;
      if (b.nextReview === null)
        return -1;
      return a.nextReview.getTime() - b.nextReview.getTime();
    });
    return allWords;
  }
  /**
   * Update a single word's review fields on its source Canvas node.
   * Write-back is debounced per canvas file.
   */
  async updateWord(word) {
    const file = await this.resolveFile(word.canvasPath);
    if (!file) {
      console.warn(
        `[Ebbinghaus] Cannot update word "${word.word}": Canvas file not found: ${word.canvasPath}`
      );
      return;
    }
    const data = await this.readCanvasFile(file);
    const node = data.nodes.find((n) => n.id === word.nodeId);
    if (!node) {
      console.warn(
        `[Ebbinghaus] Cannot update word "${word.word}": node ${word.nodeId} not found`
      );
      return;
    }
    this.applyWordToNode(word, node);
    this.debouncedWrite(file, data);
  }
  /**
   * Batch-update multiple words (may span multiple canvas files).
   * All writes are debounced per file.
   */
  async updateWords(words) {
    const groups = /* @__PURE__ */ new Map();
    for (const word of words) {
      const list = groups.get(word.canvasPath) || [];
      list.push(word);
      groups.set(word.canvasPath, list);
    }
    for (const [path, wordList] of groups) {
      const file = await this.resolveFile(path);
      if (!file)
        continue;
      const data = await this.readCanvasFile(file);
      for (const word of wordList) {
        const node = data.nodes.find((n) => n.id === word.nodeId);
        if (node) {
          this.applyWordToNode(word, node);
        }
      }
      this.debouncedWrite(file, data);
    }
  }
  // ═══════════════════════════════════════════
  // Statistics
  // ═══════════════════════════════════════════
  /** Get the stored plugin stats (loaded from data.json) */
  getStats() {
    return this.stats;
  }
  /** Replace stats entirely (used when the plugin loads) */
  setStats(stats) {
    this.stats = stats;
  }
  /**
   * Record a review result for today's stats.
   * Mutates in-memory stats — caller must persist via plugin.saveData().
   */
  recordReview(result, isNew) {
    const today = dateKey();
    const entry = this.stats.dailyStats[today] || {
      reviewed: 0,
      newLearned: 0,
      correct: 0,
      fuzzy: 0,
      wrong: 0
    };
    entry.reviewed++;
    if (isNew)
      entry.newLearned++;
    entry[result]++;
    this.stats.dailyStats[today] = entry;
    return this.stats;
  }
  // ═══════════════════════════════════════════
  // Private helpers
  // ═══════════════════════════════════════════
  /**
   * Resolve a vault-relative path to a TFile.
   * Caches the result in-memory for the lifetime of the plugin instance.
   */
  async resolveFile(path) {
    const cached = this.fileCache.get(path);
    if (cached)
      return cached;
    const file = this.vault.getAbstractFileByPath(path);
    if (!file || !file.extension) {
      console.warn(`[Ebbinghaus] Canvas file not found: ${path}`);
      return null;
    }
    const tFile = file;
    this.fileCache.set(path, tFile);
    return tFile;
  }
  /** Read and parse a Canvas JSON file */
  async readCanvasFile(file) {
    const raw = await this.vault.read(file);
    try {
      const data = JSON.parse(raw);
      data.nodes = data.nodes || [];
      data.edges = data.edges || [];
      return data;
    } catch (err) {
      console.error(`[Ebbinghaus] Failed to parse Canvas file: ${file.path}`, err);
      return { nodes: [], edges: [] };
    }
  }
  /** Extract only text-type nodes from a Canvas file */
  async readTextNodes(file) {
    const data = await this.readCanvasFile(file);
    return data.nodes.filter((n) => n.type === "text");
  }
  /** Serialize and write Canvas data back to disk, then flush the cache */
  async writeCanvasFile(file, data) {
    const json = JSON.stringify(data, null, "	");
    await this.vault.modify(file, json);
    this.fileCache.delete(file.path);
  }
  /**
   * Debounced write: delays writing to avoid rapid successive writes
   * to the same file (e.g. during a fast review session).
   */
  debouncedWrite(file, data) {
    const key = file.path;
    const existing = this.writeTimers.get(key);
    if (existing)
      clearTimeout(existing);
    const timer = setTimeout(async () => {
      this.writeTimers.delete(key);
      await this.writeCanvasFile(file, data);
    }, _DataManager.WRITE_DEBOUNCE_MS);
    this.writeTimers.set(key, timer);
  }
  /** Apply ParsedWord review fields to a CanvasNode */
  applyWordToNode(word, node) {
    node.ebbingReviewStage = word.reviewStage;
    node.ebbingNextReview = word.nextReview?.toISOString() ?? void 0;
    node.ebbingLastReview = word.lastReview?.toISOString() ?? void 0;
    node.ebbingCreatedAt = word.createdAt?.toISOString() ?? void 0;
    node.ebbingReviewHistory = word.reviewHistory;
  }
};
/** Debounce delay for batch writes (ms) */
_DataManager.WRITE_DEBOUNCE_MS = 300;
var DataManager = _DataManager;

// ebbinghaus-vocabulary/src/review-engine.ts
var ReviewEngine = class {
  constructor(settings) {
    this.settings = settings;
    this.intervals = buildActiveIntervals(settings);
    this.masteredStage = totalStages(this.intervals);
  }
  // ═══════════════════════════════════════════
  // Classification
  // ═══════════════════════════════════════════
  /**
   * Classify a word into one of three UI categories.
   *
   *   "new"     — never reviewed (stage 0, no history)
   *   "due"     — nextReview is in the past, and not yet mastered
   *   "mastered"— reached the final stage
   */
  classifyWord(word) {
    if (word.reviewStage >= this.masteredStage) {
      return "mastered";
    }
    if (word.reviewStage === 0 && (!word.reviewHistory || word.reviewHistory.length === 0)) {
      return "new";
    }
    if (word.nextReview !== null && word.nextReview.getTime() <= Date.now()) {
      return "due";
    }
    if (word.nextReview === null && word.reviewHistory.length > 0) {
      return "due";
    }
    return "due";
  }
  /**
   * Check if a word's review is currently due.
   * More precise than classifyWord — returns a boolean.
   */
  isDue(word) {
    if (word.reviewStage >= this.masteredStage)
      return false;
    if (word.nextReview === null) {
      return false;
    }
    return word.nextReview.getTime() <= Date.now();
  }
  /**
   * Check if a word is purely new (never reviewed).
   */
  isNew(word) {
    return word.reviewStage === 0 && (!word.reviewHistory || word.reviewHistory.length === 0);
  }
  /**
   * Check if a word has been mastered.
   */
  isMastered(word) {
    return word.reviewStage >= this.masteredStage;
  }
  // ═══════════════════════════════════════════
  // State Transitions
  // ═══════════════════════════════════════════
  /**
   * Apply a review result to a word.
   *
   * This mutates the word's review fields in place and returns the
   * result record that was appended to the history.
   *
   * @param word    The word being reviewed
   * @param result  "correct" | "fuzzy" | "wrong"
   * @returns       The ReviewRecord that was appended
   */
  applyReview(word, result) {
    const now = /* @__PURE__ */ new Date();
    const record = {
      date: now.toISOString(),
      result
    };
    if (!word.reviewHistory) {
      word.reviewHistory = [];
    }
    word.reviewHistory.push(record);
    word.lastReview = now;
    switch (result) {
      case "correct":
        this.handleCorrect(word, now);
        break;
      case "fuzzy":
        this.handleFuzzy(word, now);
        break;
      case "wrong":
        this.handleWrong(word, now);
        break;
    }
    return record;
  }
  /**
   * Get the interval in ms for a given stage.
   * Stage 0 has no interval (it's the "new" state).
   * Stage 1 → intervals[0], stage 2 → intervals[1], etc.
   *
   * If the stage exceeds the number of intervals, return 0
   * (the word is considered mastered and won't be reviewed).
   */
  getIntervalForStage(stage) {
    if (stage <= 0)
      return 0;
    const idx = stage - 1;
    if (idx >= this.intervals.length)
      return 0;
    return this.intervals[idx];
  }
  /**
   * Determine the display label for a stage.
   * e.g. stage 1 → "20 min", stage 3 → "1 day"
   */
  getStageLabel(stage) {
    if (stage <= 0)
      return "New";
    if (stage >= this.masteredStage)
      return "Mastered";
    const ms = this.getIntervalForStage(stage);
    return this.formatDuration(ms);
  }
  // ═══════════════════════════════════════════
  // Session-building
  // ═══════════════════════════════════════════
  /**
   * Build the list of words to include in a review session.
   *
   * Priority order:
   *   1. All "due" words (overdue longest first)
   *   2. New words up to the daily limit (if settings permit)
   *
   * @param allWords  All tracked words in the system
   * @param stats     Current stats (to compute today's new word count)
   * @returns         Words to review, in presentation order
   */
  buildReviewQueue(allWords) {
    const dueWords = [];
    const newWords = [];
    const masteredWords = [];
    const inProgressWords = [];
    for (const word of allWords) {
      if (this.isMastered(word)) {
        masteredWords.push(word);
      } else if (this.isNew(word)) {
        newWords.push(word);
      } else if (this.isDue(word)) {
        dueWords.push(word);
      } else {
        inProgressWords.push(word);
      }
    }
    dueWords.sort(
      (a, b) => (a.nextReview?.getTime() ?? 0) - (b.nextReview?.getTime() ?? 0)
    );
    newWords.sort(
      (a, b) => (a.createdAt?.getTime() ?? 0) - (b.createdAt?.getTime() ?? 0)
    );
    const limit = this.settings.dailyNewWordLimit || Infinity;
    const newToAdd = this.settings.autoIncludeNewWords ? Math.min(limit, newWords.length) : 0;
    const queue = [
      ...dueWords,
      ...newWords.slice(0, newToAdd)
    ];
    return {
      queue,
      newWordsIncluded: newToAdd
    };
  }
  // ═══════════════════════════════════════════
  // Review Scheduling Helpers
  // ═══════════════════════════════════════════
  /**
   * Schedule the next review after initial learning.
   * Call this when a NEW word is reviewed for the first time.
   *
   * @param createdAt  When the word was first learned
   * @returns          The next review date
   */
  scheduleInitialReview(createdAt) {
    const firstInterval = this.getIntervalForStage(1);
    return new Date(createdAt.getTime() + firstInterval);
  }
  // ═══════════════════════════════════════════
  // Private: State Transition Implementations
  // ═══════════════════════════════════════════
  /**
   * Handle a "correct" review result.
   * Stage increments by 1. Next review = now + full interval.
   */
  handleCorrect(word, now) {
    const newStage = Math.min(word.reviewStage + 1, this.masteredStage);
    word.reviewStage = newStage;
    if (newStage >= this.masteredStage) {
      word.nextReview = null;
    } else {
      const interval = this.getIntervalForStage(newStage);
      word.nextReview = new Date(now.getTime() + interval);
    }
  }
  /**
   * Handle a "fuzzy" review result.
   * Stage decrements by 1 (minimum 0). Next review = now + half interval.
   */
  handleFuzzy(word, now) {
    word.reviewStage = Math.max(0, word.reviewStage - 1);
    const stage = word.reviewStage === 0 ? 1 : word.reviewStage;
    const interval = this.getIntervalForStage(stage);
    word.nextReview = new Date(now.getTime() + Math.round(interval * 0.5));
  }
  /**
   * Handle a "wrong" review result.
   * Stage resets to 0. Next review = now + first interval (stage 1).
   */
  handleWrong(word, now) {
    word.reviewStage = 0;
    const firstInterval = this.getIntervalForStage(1);
    word.nextReview = new Date(now.getTime() + firstInterval);
  }
  // ═══════════════════════════════════════════
  // Utility
  // ═══════════════════════════════════════════
  /**
   * Format a duration in ms to a human-readable string.
   *
   * @example
   *   formatDuration(1_200_000)  → "20 min"
   *   formatDuration(3_600_000)  → "1 hour"
   *   formatDuration(172_800_000) → "2 days"
   */
  formatDuration(ms) {
    if (ms <= 0)
      return "\u2014";
    const minutes = Math.round(ms / 6e4);
    const hours = Math.round(ms / 36e5);
    const days = Math.round(ms / 864e5);
    if (minutes < 60)
      return `${minutes} min`;
    if (hours < 24)
      return `${hours} hour${hours > 1 ? "s" : ""}`;
    return `${days} day${days > 1 ? "s" : ""}`;
  }
};

// ebbinghaus-vocabulary/src/review-panel.ts
var import_obsidian3 = require("obsidian");

// ebbinghaus-vocabulary/src/review-modal.ts
var import_obsidian2 = require("obsidian");
var ReviewModal = class extends import_obsidian2.Modal {
  constructor(plugin, queue, onComplete) {
    super(plugin.app);
    /** Session counters */
    this.correctCount = 0;
    this.fuzzyCount = 0;
    this.wrongCount = 0;
    /** Track which words were new (first review) for stats */
    this.newWordCount = 0;
    /** DOM refs for animation targets */
    this.cardInner = null;
    this.plugin = plugin;
    this.queue = queue;
    this.currentIndex = 0;
    this.onComplete = onComplete;
  }
  onOpen() {
    const { contentEl, modalEl } = this;
    modalEl.addClass("ebbing-modal");
    contentEl.addClass("ebbing-modal-content");
    contentEl.empty();
    this.renderCard(contentEl);
    this.contentEl.setAttribute("tabindex", "-1");
    this.contentEl.focus();
  }
  onClose() {
    super.onClose();
    this.cardInner = null;
  }
  // ═══════════════════════════════════════════
  // Rendering
  // ═══════════════════════════════════════════
  /** Render the current card */
  renderCard(parent) {
    parent.empty();
    const word = this.queue[this.currentIndex];
    if (!word) {
      this.renderSummary(parent);
      return;
    }
    this.renderProgress(parent);
    const cardContainer = parent.createDiv("ebbing-card-container");
    const cardInner = cardContainer.createDiv("ebbing-card-inner");
    this.cardInner = cardInner;
    const front = cardInner.createDiv("ebbing-card-front");
    front.createDiv("ebbing-card-word").setText(word.word);
    front.createDiv("ebbing-card-hint").setText("\u70B9\u51FB\u7FFB\u8F6C\u67E5\u770B\u91CA\u4E49");
    front.addEventListener("click", () => {
      this.flipCard(cardInner, word);
    });
    const back = cardInner.createDiv("ebbing-card-back");
    back.createDiv("ebbing-card-word-back").setText(word.word);
    if (word.definition) {
      const defEl = back.createDiv("ebbing-card-section ebbing-card-definition");
      defEl.createDiv("ebbing-card-label").setText("\u91CA\u4E49");
      defEl.createDiv("ebbing-card-value").setText(word.definition);
    }
    if (word.example) {
      const exEl = back.createDiv("ebbing-card-section ebbing-card-example");
      exEl.createDiv("ebbing-card-label").setText("\u4F8B\u53E5");
      exEl.createDiv("ebbing-card-value").setText(word.example);
    }
    if (word.exampleTranslation) {
      const transEl = back.createDiv("ebbing-card-section ebbing-card-translation");
      transEl.createDiv("ebbing-card-label").setText("\u7FFB\u8BD1");
      transEl.createDiv("ebbing-card-value").setText(word.exampleTranslation);
    }
    if (word.construction) {
      const constrEl = back.createDiv("ebbing-card-section ebbing-card-construction");
      constrEl.createDiv("ebbing-card-label").setText("\u6784\u6210");
      constrEl.createDiv("ebbing-card-value").setText(word.construction);
    }
    const buttonsEl = back.createDiv("ebbing-card-buttons");
    this.createFeedbackButton(buttonsEl, "\u274C \u4E0D\u8BA4\u8BC6", "wrong", word);
    this.createFeedbackButton(buttonsEl, "\u{1F914} \u6A21\u7CCA", "fuzzy", word);
    this.createFeedbackButton(buttonsEl, "\u2705 \u8BA4\u8BC6", "correct", word);
    const hintEl = back.createDiv("ebbing-card-keyhint");
    hintEl.setText("\u952E\u76D8: \u7A7A\u683C=\u7FFB\u8F6C  E=\u8BA4\u8BC6  W=\u6A21\u7CCA  Q=\u4E0D\u8BA4\u8BC6");
  }
  /** Create a feedback button with click handler */
  createFeedbackButton(parent, text, result, word) {
    const btn = parent.createEl("button", {
      text,
      cls: `ebbing-feedback-btn ebbing-feedback-${result}`,
      attr: { tabindex: "-1" }
    });
    btn.addEventListener("click", async () => {
      await this.handleFeedback(word, result);
    });
  }
  /** Progress bar and counter */
  renderProgress(parent) {
    const progressEl = parent.createDiv("ebbing-progress");
    const barWrapper = progressEl.createDiv("ebbing-progress-bar-wrapper");
    const bar = barWrapper.createDiv("ebbing-progress-bar");
    const pct = this.currentIndex / this.queue.length * 100;
    bar.style.width = `${pct}%`;
    progressEl.createDiv("ebbing-progress-text").setText(
      `${this.currentIndex + 1} / ${this.queue.length}`
    );
  }
  /** Session completion summary */
  renderSummary(parent) {
    parent.empty();
    const summaryEl = parent.createDiv("ebbing-summary");
    summaryEl.createDiv("ebbing-summary-emoji").setText("\u{1F389}");
    summaryEl.createDiv("ebbing-summary-title").setText("\u590D\u4E60\u5B8C\u6210\uFF01");
    const statsEl = summaryEl.createDiv("ebbing-summary-stats");
    const total = this.correctCount + this.fuzzyCount + this.wrongCount;
    const accuracy = total > 0 ? Math.round(this.correctCount / total * 100) : 0;
    statsEl.createDiv("ebbing-summary-row").setText(
      `\u2705 \u8BA4\u8BC6\uFF1A${this.correctCount}`
    );
    statsEl.createDiv("ebbing-summary-row").setText(
      `\u{1F914} \u6A21\u7CCA\uFF1A${this.fuzzyCount}`
    );
    statsEl.createDiv("ebbing-summary-row").setText(
      `\u274C \u4E0D\u8BA4\u8BC6\uFF1A${this.wrongCount}`
    );
    statsEl.createDiv("ebbing-summary-row ebbing-summary-accuracy").setText(
      `\u6B63\u786E\u7387\uFF1A${accuracy}%`
    );
    const closeBtn = summaryEl.createEl("button", {
      text: "\u5173\u95ED",
      cls: "ebbing-summary-close"
    });
    closeBtn.addEventListener("click", () => {
      this.close();
    });
  }
  // ═══════════════════════════════════════════
  // Interaction
  // ═══════════════════════════════════════════
  /** Flip the card to show the back face */
  flipCard(cardInner, _word) {
    if (cardInner.hasClass("ebbing-flipped"))
      return;
    cardInner.addClass("ebbing-flipped");
  }
  /**
   * Handle a review feedback selection.
   *  1. Apply the review via ReviewEngine
   *  2. Record stats
   *  3. Persist to Canvas
   *  4. Advance to next card (or summary)
   */
  async handleFeedback(word, result) {
    const engine = this.plugin.reviewEngine;
    const oldStage = word.reviewStage;
    const isNew = engine.isNew(word);
    engine.applyReview(word, result);
    this.plugin.dataManager.recordReview(result, isNew);
    switch (result) {
      case "correct":
        this.correctCount++;
        break;
      case "fuzzy":
        this.fuzzyCount++;
        break;
      case "wrong":
        this.wrongCount++;
        break;
    }
    if (isNew)
      this.newWordCount++;
    if (oldStage < 8 && word.reviewStage >= 8) {
    }
    this.plugin.dataManager.updateWord(word);
    await this.plugin.saveData(this.plugin.settings);
    this.currentIndex++;
    if (this.currentIndex >= this.queue.length) {
      this.renderSummary(this.contentEl);
    } else {
      this.renderCard(this.contentEl);
    }
  }
  // ═══════════════════════════════════════════
  // Keyboard Navigation
  // ═══════════════════════════════════════════
  /** Handle keyboard input for efficiency */
  onKeyDown(event) {
    const word = this.queue[this.currentIndex];
    if (!word)
      return;
    if (event.key === " " || event.code === "Space") {
      event.preventDefault();
      event.stopPropagation();
      if (this.cardInner && !this.cardInner.hasClass("ebbing-flipped")) {
        this.flipCard(this.cardInner, word);
      }
      return;
    }
    if (!this.cardInner?.hasClass("ebbing-flipped"))
      return;
    switch (event.key.toLowerCase()) {
      case "e":
        this.handleFeedback(word, "correct");
        event.preventDefault();
        break;
      case "w":
        this.handleFeedback(word, "fuzzy");
        event.preventDefault();
        break;
      case "q":
        this.handleFeedback(word, "wrong");
        event.preventDefault();
        break;
    }
  }
};

// ebbinghaus-vocabulary/src/stats-heatmap.ts
var StatsHeatmap = class {
  constructor(container, stats, colors) {
    // ═══════════════════════════════════════════
    // Tooltip
    // ═══════════════════════════════════════════
    this.tooltipEl = null;
    this.container = container;
    this.stats = stats;
    this.colors = colors;
  }
  /**
   * Render the full heatmap into the container.
   * Replaces any existing content.
   */
  render() {
    this.container.empty();
    const wrapper = this.container.createDiv("ebbing-heatmap");
    wrapper.style.setProperty(
      "display",
      "grid"
    );
    const today = /* @__PURE__ */ new Date();
    const cells = this.buildCells(today);
    const dayLabels = ["", "\u4E00", "", "\u4E09", "", "\u4E94", ""];
    const monthLabels = this.buildMonthLabels(cells);
    const totalCols = cells[0]?.length ?? 0;
    const grid = wrapper.createDiv("ebbing-heatmap-grid");
    const monthRow = grid.createDiv("ebbing-heatmap-months");
    monthRow.createDiv("ebbing-heatmap-spacer");
    for (let col = 0; col < totalCols; col++) {
      const label = monthLabels[col] ?? "";
      const cell = monthRow.createDiv("ebbing-heatmap-month-label");
      cell.setText(label);
    }
    for (let row = 0; row < 7; row++) {
      const dayRow = grid.createDiv("ebbing-heatmap-row");
      const labelEl = dayRow.createDiv("ebbing-heatmap-day-label");
      labelEl.setText(dayLabels[row]);
      for (let col = 0; col < totalCols; col++) {
        const cellData = cells[row]?.[col];
        const cellEl = dayRow.createDiv("ebbing-heatmap-cell");
        if (cellData) {
          const level = heatmapLevel(cellData.count);
          cellEl.style.backgroundColor = this.colors[level] ?? this.colors[0];
          cellEl.setAttribute("data-level", String(level));
          cellEl.setAttribute("data-date", cellData.dateKey);
          cellEl.setAttribute("data-count", String(cellData.count));
          cellEl.addEventListener("mouseenter", (ev) => {
            this.showTooltip(ev, cellEl, cellData);
          });
          cellEl.addEventListener("mouseleave", () => {
            this.hideTooltip();
          });
        } else {
          cellEl.addClass("ebbing-heatmap-empty");
        }
      }
    }
    this.renderLegend(wrapper);
  }
  // ═══════════════════════════════════════════
  // Grid Construction
  // ═══════════════════════════════════════════
  /**
   * Build a 7-row grid of cells covering the last 365 days.
   *
   * Row 0 = Monday (ISO weekday 1), Row 6 = Sunday (ISO weekday 7).
   * Column 0 = the oldest week, Column N-1 = this week.
   *
   * @returns 7×N matrix, each cell: { dateKey, count }
   */
  buildCells(today) {
    const startDate = this.getStartDate(today);
    const totalDays = 365;
    const rows = 7;
    const cells = Array.from(
      { length: rows },
      () => []
    );
    for (let d = 0; d < totalDays; d++) {
      const date = new Date(startDate);
      date.setDate(date.getDate() + d);
      const key = dateKey(date);
      const isoWeekday = this.getISOWeekday(date);
      const row = isoWeekday - 1;
      const dayOffset = d;
      const col = Math.floor(dayOffset / 7);
      const statEntry = this.stats.dailyStats[key];
      const count = statEntry ? statEntry.reviewed : 0;
      if (!cells[row])
        cells[row] = [];
      cells[row][col] = { dateKey: key, count };
    }
    const maxCols = Math.max(...cells.map((r) => r.length));
    for (const row of cells) {
      while (row.length < maxCols) {
        row.push(null);
      }
    }
    return cells;
  }
  /**
   * Get the start date: 365 days ago from today, snapped back to Monday.
   */
  getStartDate(today) {
    const d = new Date(today);
    d.setDate(d.getDate() - 364);
    const isoWeekday = this.getISOWeekday(d);
    const offset = isoWeekday - 1;
    d.setDate(d.getDate() - offset);
    return d;
  }
  /**
   * ISO weekday: 1 (Monday) through 7 (Sunday).
   */
  getISOWeekday(date) {
    const day = date.getDay();
    return day === 0 ? 7 : day;
  }
  /**
   * Build month labels for column headers.
   * Returns an array where each column index maps to a month label
   * (or empty string if the month hasn't changed).
   */
  buildMonthLabels(cells) {
    const colCount = cells[0]?.length ?? 0;
    const labels = [];
    let lastMonth = -1;
    const startDate = this.getStartDate(/* @__PURE__ */ new Date());
    for (let col = 0; col < colCount; col++) {
      let month = -1;
      for (const row of cells) {
        const cell = row[col];
        if (cell) {
          const d = new Date(cell.dateKey);
          month = d.getMonth();
          break;
        }
      }
      if (month !== -1 && month !== lastMonth) {
        const monthNames = [
          "1\u6708",
          "2\u6708",
          "3\u6708",
          "4\u6708",
          "5\u6708",
          "6\u6708",
          "7\u6708",
          "8\u6708",
          "9\u6708",
          "10\u6708",
          "11\u6708",
          "12\u6708"
        ];
        labels[col] = monthNames[month];
        lastMonth = month;
      } else {
        labels[col] = "";
      }
    }
    return labels;
  }
  showTooltip(event, _cell, data) {
    if (!this.tooltipEl) {
      this.tooltipEl = document.body.createDiv("ebbing-heatmap-tooltip");
    }
    const stat = this.stats.dailyStats[data.dateKey];
    const correct = stat?.correct ?? 0;
    const total = stat?.reviewed ?? 0;
    const accuracy = total > 0 ? Math.round(correct / total * 100) : 0;
    this.tooltipEl.innerHTML = `
      <div class="ebbing-tooltip-date">${data.dateKey}</div>
      <div class="ebbing-tooltip-reviews">${data.count} \u6B21\u590D\u4E60</div>
      <div class="ebbing-tooltip-accuracy">\u6B63\u786E\u7387 ${accuracy}%</div>
    `;
    const offset = 12;
    this.tooltipEl.style.left = `${event.clientX + offset}px`;
    this.tooltipEl.style.top = `${event.clientY + offset}px`;
    this.tooltipEl.style.display = "block";
  }
  hideTooltip() {
    if (this.tooltipEl) {
      this.tooltipEl.style.display = "none";
    }
  }
  // ═══════════════════════════════════════════
  // Legend
  // ═══════════════════════════════════════════
  /** Render the "Less — More" colour legend at the bottom */
  renderLegend(parent) {
    const legend = parent.createDiv("ebbing-heatmap-legend");
    legend.createSpan("ebbing-heatmap-legend-label").setText("\u5C11");
    for (let i = 0; i < 5; i++) {
      const swatch = legend.createDiv("ebbing-heatmap-legend-swatch");
      swatch.style.backgroundColor = this.colors[i];
    }
    legend.createSpan("ebbing-heatmap-legend-label").setText("\u591A");
  }
};
/** Pixel dimensions */
StatsHeatmap.CELL_SIZE = 12;
StatsHeatmap.CELL_GAP = 3;
StatsHeatmap.LABEL_WIDTH = 28;

// ebbinghaus-vocabulary/src/review-panel.ts
var ReviewPanel = class extends import_obsidian3.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    /** Currently selected tab */
    this.activeTab = "due";
    /** Loaded word data (refreshed on each render) */
    this.dueWords = [];
    this.newWords = [];
    this.masteredWords = [];
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_REVIEW;
  }
  getDisplayText() {
    return "Ebbinghaus Vocabulary";
  }
  getIcon() {
    return "book-open";
  }
  async onOpen() {
    await this.refresh();
  }
  // ═══════════════════════════════════════════
  // Refresh Cycle
  // ═══════════════════════════════════════════
  /** Re-read all data from Canvas files and re-render the panel */
  async refresh() {
    const engine = this.plugin.reviewEngine;
    const allWords = await this.plugin.dataManager.loadAllWords();
    this.dueWords = allWords.filter((w) => engine.isDue(w));
    this.newWords = allWords.filter((w) => engine.isNew(w));
    this.masteredWords = allWords.filter((w) => engine.isMastered(w));
    this.render();
  }
  // ═══════════════════════════════════════════
  // Render
  // ═══════════════════════════════════════════
  render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("ebbing-panel");
    this.renderStats(container);
    this.renderTabs(container);
    this.renderWordList(container);
    this.renderCTA(container);
    this.renderHeatmap(container);
  }
  /** Stats overview bar */
  renderStats(parent) {
    const statsEl = parent.createDiv("ebbing-stats-overview");
    const stats = this.plugin.dataManager.getStats();
    const totalReviewed = Object.values(stats.dailyStats).reduce(
      (sum, d) => sum + d.reviewed,
      0
    );
    const cards = [
      { label: "\u5F85\u590D\u4E60", value: String(this.dueWords.length), cls: "due" },
      { label: "\u65B0\u5B66", value: String(this.newWords.length), cls: "new" },
      { label: "\u5DF2\u638C\u63E1", value: String(this.masteredWords.length), cls: "mastered" },
      { label: "\u603B\u5355\u8BCD", value: String(this.dueWords.length + this.newWords.length + this.masteredWords.length), cls: "total" }
    ];
    for (const card of cards) {
      const cardEl = statsEl.createDiv(`ebbing-stat-card ebbing-stat-${card.cls}`);
      cardEl.createSpan("ebbing-stat-value").setText(card.value);
      cardEl.createSpan("ebbing-stat-label").setText(card.label);
    }
  }
  /** Tab bar for category switching */
  renderTabs(parent) {
    const tabsEl = parent.createDiv("ebbing-tabs");
    const tabs = [
      { id: "due", label: "\u5F85\u590D\u4E60", count: this.dueWords.length },
      { id: "new", label: "\u65B0\u5B66", count: this.newWords.length },
      { id: "mastered", label: "\u5DF2\u638C\u63E1", count: this.masteredWords.length }
    ];
    for (const tab of tabs) {
      const tabEl = tabsEl.createDiv("ebbing-tab");
      if (tab.id === this.activeTab) {
        tabEl.addClass("ebbing-tab-active");
      }
      tabEl.createSpan("ebbing-tab-label").setText(tab.label);
      tabEl.createSpan("ebbing-tab-count").setText(String(tab.count));
      tabEl.addEventListener("click", () => {
        this.activeTab = tab.id;
        this.render();
      });
    }
  }
  /** Scrollable word card list */
  renderWordList(parent) {
    const listEl = parent.createDiv("ebbing-word-list");
    const words = this.getActiveWords();
    if (words.length === 0) {
      const emptyEl = listEl.createDiv("ebbing-empty-state");
      emptyEl.createSpan().setText("\u2728");
      emptyEl.createDiv("ebbing-empty-text").setText(this.getEmptyMessage());
      return;
    }
    for (const word of words) {
      this.renderWordCard(listEl, word);
    }
  }
  /** Single word card in the list */
  renderWordCard(parent, word) {
    const engine = this.plugin.reviewEngine;
    const card = parent.createDiv("ebbing-word-card");
    const left = card.createDiv("ebbing-word-info");
    left.createDiv("ebbing-word-text").setText(word.word);
    const meta = left.createDiv("ebbing-word-meta");
    const stageLabel = engine.getStageLabel(word.reviewStage);
    meta.createSpan("ebbing-word-stage").setText(`Stage ${word.reviewStage} \xB7 ${stageLabel}`);
    const right = card.createDiv("ebbing-word-time");
    if (word.nextReview) {
      const isOverdue = word.nextReview.getTime() < Date.now();
      const timeStr = this.formatRelativeTime(word.nextReview);
      right.createSpan(`ebbing-time ${isOverdue ? "ebbing-overdue" : ""}`).setText(isOverdue ? `\u8FC7\u671F ${timeStr}` : `${timeStr} \u540E`);
    } else if (word.reviewStage >= 8) {
      right.createSpan("ebbing-time ebbing-mastered-check").setText("\u2713");
    } else {
      right.createSpan("ebbing-time").setText("\u65B0\u5355\u8BCD");
    }
    card.addEventListener("click", () => {
      card.toggleClass("ebbing-word-card-expanded", !card.hasClass("ebbing-word-card-expanded"));
      const existing = card.querySelector(".ebbing-word-detail");
      if (card.hasClass("ebbing-word-card-expanded")) {
        if (!existing) {
          const detail = card.createDiv({ cls: "ebbing-word-detail" });
          if (word.definition) {
            detail.createDiv({ cls: "ebbing-detail-row" }).setText(word.definition);
          }
          if (word.example) {
            const exampleRow = detail.createDiv({ cls: "ebbing-detail-row ebbing-detail-example" });
            exampleRow.setText(word.example);
          }
          if (word.exampleTranslation) {
            const transRow = detail.createDiv({ cls: "ebbing-detail-row ebbing-detail-translation" });
            transRow.setText(word.exampleTranslation);
          }
        }
      } else {
        existing?.remove();
      }
    });
  }
  /** CTA button to start reviewing */
  renderCTA(parent) {
    const ctaEl = parent.createDiv("ebbing-cta-wrapper");
    const btn = ctaEl.createEl("button", {
      text: "\u{1F680}  \u5F00\u59CB\u590D\u4E60",
      cls: "ebbing-cta-button"
    });
    btn.addEventListener("click", async () => {
      const { queue } = this.plugin.reviewEngine.buildReviewQueue([
        ...this.dueWords,
        ...this.newWords,
        ...this.masteredWords
      ]);
      if (queue.length === 0) {
        const notice = ctaEl.createDiv("ebbing-notice");
        notice.setText("\u{1F389} \u6682\u65E0\u5F85\u590D\u4E60\u5355\u8BCD\uFF01");
        setTimeout(() => notice.remove(), 3e3);
        return;
      }
      const modal = new ReviewModal(this.plugin, queue, async () => {
        await this.refresh();
        await this.plugin.refreshStatusBar();
      });
      modal.open();
    });
  }
  /** GitHub-style heatmap at the bottom */
  renderHeatmap(parent) {
    const heatmapEl = parent.createDiv("ebbing-heatmap-wrapper");
    heatmapEl.createDiv("ebbing-heatmap-title").setText("\u{1F4C8} \u5B66\u4E60\u70ED\u529B\u56FE");
    const heatmap = new StatsHeatmap(
      heatmapEl,
      this.plugin.dataManager.getStats(),
      this.plugin.settings.heatmapColors
    );
    heatmap.render();
  }
  // ═══════════════════════════════════════════
  // Helpers
  // ═══════════════════════════════════════════
  getActiveWords() {
    switch (this.activeTab) {
      case "due":
        return this.dueWords;
      case "new":
        return this.newWords;
      case "mastered":
        return this.masteredWords;
    }
  }
  getEmptyMessage() {
    switch (this.activeTab) {
      case "due":
        return "\u6CA1\u6709\u5F85\u590D\u4E60\u7684\u5355\u8BCD";
      case "new":
        return "\u6CA1\u6709\u65B0\u5355\u8BCD";
      case "mastered":
        return "\u8FD8\u6CA1\u6709\u5DF2\u638C\u63E1\u7684\u5355\u8BCD";
    }
  }
  /**
   * Format a relative time string for display.
   *
   * @example
   *   "3 小时后" / "2 天前" / "刚刚"
   */
  formatRelativeTime(date) {
    const now = Date.now();
    const diffMs = date.getTime() - now;
    const absMs = Math.abs(diffMs);
    const prefix = diffMs < 0 ? "" : "";
    const suffix = diffMs < 0 ? "\u524D" : "\u540E";
    if (absMs < 6e4)
      return "\u521A\u521A";
    if (absMs < 36e5)
      return `${Math.round(absMs / 6e4)} \u5206\u949F${suffix}`;
    if (absMs < 864e5)
      return `${Math.round(absMs / 36e5)} \u5C0F\u65F6${suffix}`;
    const days = Math.round(absMs / 864e5);
    return `${prefix}${days} \u5929${suffix}`;
  }
};

// ebbinghaus-vocabulary/main.ts
var EbbinghausVocabPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    /** Status bar item showing the daily review count */
    this.statusBarItem = null;
  }
  async onload() {
    await this.loadSettings();
    this.wordParser = new WordParser();
    this.initCoreComponents();
    this.addSettingTab(new EbbinghausSettingTab(this.app, this));
    this.registerView(
      VIEW_TYPE_REVIEW,
      (leaf) => new ReviewPanel(leaf, this)
    );
    this.addRibbonIcon("book-open", "Ebbinghaus Vocabulary", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-review-panel",
      name: "Open review panel",
      callback: () => this.activateView()
    });
    this.statusBarItem = this.addStatusBarItem();
    this.statusBarItem.addClass("ebbing-status-bar");
    this.statusBarItem.setText("\u{1F4DA} ...");
    this.statusBarItem.addEventListener("click", () => this.activateView());
    this.registerInterval(
      window.setInterval(() => this.refreshStatusBar(), 6e4)
    );
    await this.refreshStatusBar();
  }
  /** Create (or re-create) components that depend on settings */
  initCoreComponents() {
    this.dataManager = new DataManager(this.app.vault, this.settings);
    this.reviewEngine = new ReviewEngine(this.settings);
  }
  /** Open the review panel in the right sidebar */
  async activateView() {
    const { workspace } = this.app;
    const existing = workspace.getLeavesOfType(VIEW_TYPE_REVIEW);
    if (existing.length > 0) {
      workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = workspace.getRightLeaf(false);
    if (leaf) {
      await leaf.setViewState({
        type: VIEW_TYPE_REVIEW,
        active: true
      });
      workspace.revealLeaf(leaf);
    }
  }
  /** Update the status bar with the current review count */
  async refreshStatusBar() {
    if (!this.statusBarItem)
      return;
    try {
      const allWords = await this.dataManager.loadAllWords();
      const dueCount = allWords.filter(
        (w) => this.reviewEngine.classifyWord(w) === "due"
      ).length;
      if (dueCount > 0) {
        this.statusBarItem.setText(`\u{1F4DA} ${dueCount}`);
        this.statusBarItem.setAttribute("aria-label", `${dueCount} words due for review`);
      } else {
        this.statusBarItem.setText("\u{1F4DA} \u2713");
        this.statusBarItem.setAttribute("aria-label", "No words due");
      }
    } catch {
      this.statusBarItem.setText("\u{1F4DA} !");
    }
  }
  /** Load settings from plugin data, merging with defaults */
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  /** Persist settings to plugin data */
  async saveSettings() {
    await this.saveData(this.settings);
    this.initCoreComponents();
    this.refreshStatusBar();
  }
  onunload() {
  }
};
